FROM public.ecr.aws/lambda/python:3.11

COPY requirements.txt .
RUN pip install -r requirements.txt -t /var/task/

COPY app /var/task/app
COPY lambda_function.py /var/task/

CMD ["lambda_function.handler"]
